#version: '3'
services:
  app-dev:
    build:
      context: .
      dockerfile: build/app/Dockerfile.local
    ports:
      - "3002:8080"
    volumes:
      - .:/go/src/app
    environment:
      - ENVIRONMENT=local
    tty: true
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lessonlink
      TZ: 'Asia/Tokyo'
    ports:
      - "23306:3306"
    volumes:
      - ./data-volume:/var/lib/mysql
      - ./entrypoint/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3003:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions